"""Add ON DELETE CASCADE to project_item

Revision ID: 4a40dfa8b65f
Revises: cf6a8fb1fd44
Create Date: 2025-05-22 16:40:57.950308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a40dfa8b65f'
down_revision = 'cf6a8fb1fd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_item', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('parameter1',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('parameter2',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('parameter3',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('project_item_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_item_project_id_fkey', 'project', ['project_id'], ['id'])
        batch_op.alter_column('parameter3',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('parameter2',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('parameter1',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
