"""Initial migration

Revision ID: bd1046019404
Revises: 
Create Date: 2020-12-06 21:44:18.071169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1046019404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sil', sa.String(), nullable=False),
    sa.Column('analysis', sa.String(), nullable=False),
    sa.Column('parameter1DirectlyProportional', sa.String(), nullable=False),
    sa.Column('parameter1Min', sa.String(), nullable=False),
    sa.Column('parameter1Max', sa.String(), nullable=False),
    sa.Column('parameter2DirectlyProportional', sa.String(), nullable=False),
    sa.Column('parameter2Min', sa.String(), nullable=False),
    sa.Column('parameter2Max', sa.String(), nullable=False),
    sa.Column('parameter3DirectlyProportional', sa.String(), nullable=False),
    sa.Column('parameter3Min', sa.String(), nullable=False),
    sa.Column('parameter3Max', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('parameter1', sa.String(), nullable=True),
    sa.Column('parameter2', sa.String(), nullable=True),
    sa.Column('parameter3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_item')
    op.drop_table('project')
    # ### end Alembic commands ###
